# stock_market_dataset
head and tail of excel sheet
head(stock_market_dataset)
# A tibble: 6 × 39
   ...1 Date     Natural_Gas_Price Natural_Gas_Vol. Crude_oil_Price Crude_oil_Vol. Copper_Price
  <dbl> <chr>                <dbl>            <dbl>           <dbl>          <dbl>        <dbl>
1     0 02-02-2…              2.08               NA            72.3             NA         3.82
2     1 01-02-2…              2.05           161340            73.8         577940         3.85
3     2 31-01-2…              2.1            142860            75.8         344490         3.91
4     3 30-01-2…              2.08           139750            77.8         347240         3.91
5     4 29-01-2…              2.49             3590            76.8         331930         3.88
6     5 26-01-2…              2.71            73020            78.0         365460         3.85
# ℹ 32 more variables: Copper_Vol. <dbl>, Bitcoin_Price <chr>, Bitcoin_Vol. <dbl>,
#   Platinum_Price <chr>, Platinum_Vol. <dbl>, Ethereum_Price <chr>, Ethereum_Vol. <dbl>,
#   `S&P_500_Price` <chr>, Nasdaq_100_Price <chr>, Nasdaq_100_Vol. <dbl>, Apple_Price <dbl>,
#   Apple_Vol. <dbl>, Tesla_Price <dbl>, Tesla_Vol. <dbl>, Microsoft_Price <dbl>,
#   Microsoft_Vol. <dbl>, Silver_Price <dbl>, Silver_Vol. <dbl>, Google_Price <dbl>,
#   Google_Vol. <dbl>, Nvidia_Price <dbl>, Nvidia_Vol. <dbl>, Berkshire_Price <chr>,
#   Berkshire_Vol. <dbl>, Netflix_Price <dbl>, Netflix_Vol. <dbl>, Amazon_Price <dbl>, …
> tail(Stock_Market_Dataset)
# A tibble: 6 × 39
   ...1 Date     Natural_Gas_Price Natural_Gas_Vol. Crude_oil_Price Crude_oil_Vol. Copper_Price
  <dbl> <chr>                <dbl>            <dbl>           <dbl>          <dbl>        <dbl>
1  1237 11-02-2…              2.64           202420            52.4         750240         2.79
2  1238 08-02-2…              2.58           147880            52.7         621000         2.81
3  1239 07-02-2…              2.55           211790            52.6         749010         2.83
4  1240 06-02-2…              2.66            98330            54.0         606720         2.84
5  1241 05-02-2…              2.66            82250            53.7         609760         2.82
6  1242 04-02-2…              2.66           116490            54.6         622470         2.80
# ℹ 32 more variables: Copper_Vol. <dbl>, Bitcoin_Price <chr>, Bitcoin_Vol. <dbl>,
#   Platinum_Price <chr>, Platinum_Vol. <dbl>, Ethereum_Price <chr>, Ethereum_Vol. <dbl>,
#   `S&P_500_Price` <chr>, Nasdaq_100_Price <chr>, Nasdaq_100_Vol. <dbl>, Apple_Price <dbl>,
#   Apple_Vol. <dbl>, Tesla_Price <dbl>, Tesla_Vol. <dbl>, Microsoft_Price <dbl>,
#   Microsoft_Vol. <dbl>, Silver_Price <dbl>, Silver_Vol. <dbl>, Google_Price <dbl>,
#   Google_Vol. <dbl>, Nvidia_Price <dbl>, Nvidia_Vol. <dbl>, Berkshire_Price <chr>,
#   Berkshire_Vol. <dbl>, Netflix_Price <dbl>, Netflix_Vol. <dbl>, Amazon_Price <dbl>, …
> 